# Generated by Django 4.1.3 on 2023-01-07 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_category_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(default='uncategorized', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='profile_pic',
            field=models.ImageField(upload_to='thumbnail/'),
        ),
    ]
